apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline-sa
imagePullSecrets:
  - name: quay-registry-secret
  - name: redhat-registry-secret
secrets:
  - name: github-token
  - name: quay-registry-secret
  - name: redhat-registry-secret