kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipeline-sa-edit-rolebinding
  namespace: test-quarkus
subjects:
- kind: ServiceAccount
  name: pipeline-sa
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io